/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Wed, 23 Apr 2025 14:57:05 GMT
///
import type { CreateShopDto } from "./create-shop.dto";
export class UpdateShopDto extends PartialType(CreateShopDto) {}
