/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Wed, 23 Apr 2025 14:57:05 GMT
///
/// Parent module: blackjackModule
/// Controller: "blackjackController" registered as "blackjack" (5 routes)

import { request } from "../central";
import type { CreateBlackjackBetDto } from "../_types/src/modules/spinData/blackjack/dto/create-blackjackBet.dto";

export default {
  // GET @ /blackjack/bets
  findManyBets(
    params: {},
    body: {},
    query: { crudQuery: string }
  ): Promise<{
    data: any;
    totalRecords: any;
    pageCount: number;
    page: number;
    pageSize: number;
    orderBy: any[];
  }> {
    return request("GET", `/blackjack/bets`, body, query);
  },

  // GET @ /blackjack/tables
  findManyTables(
    params: {},
    body: {},
    query: { crudQuery: string }
  ): Promise<{
    data: any;
    totalRecords: any;
    pageCount: number;
    page: number;
    pageSize: number;
    orderBy: any[];
  }> {
    return request("GET", `/blackjack/tables`, body, query);
  },

  // GET @ /blackjack/:blackJackId
  getGameBlackjackBet(
    params: { blackJackId: string },
    body: {} = {},
    query: {} = {}
  ): Promise<any> {
    return request("GET", `/blackjack/${params.blackJackId}`, body, query);
  },

  // GET @ /blackjack/winners/:blackJackId
  getGameWinners(
    params: { blackJackId: string },
    body: {} = {},
    query: {} = {}
  ): Promise<any> {
    return request(
      "GET",
      `/blackjack/winners/${params.blackJackId}`,
      body,
      query
    );
  },

  // POST @ /blackjack
  create(
    params: {},
    body: CreateBlackjackBetDto,
    query: { crudQuery: string }
  ): Promise<any> {
    return request("POST", `/blackjack`, body, query);
  },
};
