/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Wed, 23 Apr 2025 14:57:05 GMT
///

export class RTGSettingsRequestDto {
  public token: string;
  public gameId: string;
  public userData: {
    userId: string;
    hash: string;
    affiliate: string;
    lang: string;
    channel: string;
    userType: string;
    fingerprint: string;
  };
  public custom: { siteId: string; extras: string };
}
