/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Wed, 23 Apr 2025 14:57:05 GMT
///

export class RTGSpinRequestDto {
  public gameId: string;
  public custom: { siteId: string; extras: string };
  public bonusId: any;
  public extras: any;
  public siteId: string;
  public userType: string;
  public lang: number;
  public fingerprint: number;
  public channel: number;
  public affiliate: number;
  public userData: {
    userId: number;
    affiliate: string;
    lang: string;
    channel: string;
    userType: string;
  };
  public token: string;
  public stake: number;
  public sessionId: string;
  public playMode: string;
}
