/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Wed, 23 Apr 2025 14:57:05 GMT
///
/// Parent module: appModule
/// Controller: "gameController" registered as "game" (0 routes)

import { request } from "../central";

export default {};
