/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Wed, 23 Apr 2025 14:57:05 GMT
///
/// Parent module: authModule
/// Controller: "authController" registered as "auth" (5 routes)

import { cashflowClient } from '..'

export const authController = {
  // POST @ /auth/login
  login(params: {}, body: { username: string; password: string }, query: {} = {}): Promise<any> {
    // const network = new Network()
    return cashflowClient.request('POST', `/auth/login`, body, query)
  },

  // GET @ /auth/ip
  getIpAddress(params: {} = {}, body: {} = {}, query: {} = {}): Promise<string> {
    return cashflowClient.request('GET', `/auth/ip`, body, query)
  },

  // GET @ /auth/logout
  logout(params: {} = {}, body: {} = {}, query: {} = {}): Promise<void> {
    return cashflowClient.request('GET', `/auth/logout`, body, query)
  },

  // POST @ /auth/register
  register(params: {}, body: any, query: {} = {}): Promise<any> {
    return cashflowClient.request('POST', `/auth/register`, body, query)
  },

  // POST @ /auth/checkname
  checkname(params: {}, body: any, query: {} = {}): Promise<boolean> {
    return cashflowClient.request('POST', `/auth/checkname`, body, query)
  },
}
// export { default as authController } from './authController'
