/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Wed, 23 Apr 2025 14:57:05 GMT
///

export interface UserWithProfile extends userWithProfile {}
export type Gender =
  | "BOY"
  | "GIRL"
  | "ALIEN"
  | "UNSURE"
  | "ROBOT"
  | "COMPLICATED";
export interface IUser {
  id: string;
  phpid: number | null;
  username: string;
  email: string | null;
  age: number | null;
  gender: Gender;
  location: string | null;
  accessToken: string | null;
  password: string;
  avatar: string | null;
  isAnonymous: boolean | null;
  dateOfBirth: Date | null;
  phone: string | null;
  status: UserStatus;
  twoFactorEnabled: boolean | null;
  emailVerified: boolean | null;
  lastLogin: Date | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  isOnline: boolean | null;
  cashtag: string | null;
  isStaff: boolean | null;
  currentSessionId: string | null;
  activeProfileId: string | null;
  lastDailySpin: Date | null;
  vipRankLevel: number | null;
  // shop: Shop
  purchases: Transaction[];
  balance: number;
  vipPoints: number;
  countBalance: number;
  currency: string | null;
  isExcluded: boolean | null;
  isActive: boolean;
  faceVerificationTime: string | null;
  address: number | null;
  totalCashOut: number | null;
  totalSpins: number;
  totalCashIn: number | null;
  totalWon: number | null;
  totalBet: number | null;
  totalBonusWon: number | null;
  rtp: number | null;
  profileType: ProfileType;
  xp: number | null;
  verifiedAt: Date | null;
  phpShopId: number | null;
}
